TERMUX_PKG_HOMEPAGE=https://github.com/apple/swift-corelibs-libdispatch
TERMUX_PKG_DESCRIPTION="The libdispatch project, for concurrency on multicore hardware"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@buttaface"
_VERSION=5.4
TERMUX_PKG_VERSION=1:${_VERSION}
TERMUX_PKG_SRCURL=https://github.com/apple/swift-corelibs-libdispatch/archive/swift-${_VERSION}-DEVELOPMENT-SNAPSHOT-2021-01-11-a.tar.gz
TERMUX_PKG_SHA256=f34b33bf025cff5fcafff09cefce9c758f5b49aa2ac13657f5d3456464af8a8c
TERMUX_PKG_DEPENDS="libc++, libblocksruntime"
